repos:
  -   repo: https://github.com/pycqa/isort
      rev: 5.10.1
      hooks:
      - id: isort
        language_version: python3
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.31.1
    hooks:
      - id: pyupgrade
        args:
          - --py37-plus
  -   repo: https://github.com/psf/black
      rev: 22.1.0
      hooks:
      - id: black
        language_version: python3
        exclude: versioneer.py
        args:
          - --target-version=py37
  -   repo: https://github.com/PyCQA/flake8
      rev: 4.0.1
      hooks:
      - id: flake8
        language_version: python3
